"""add likes to replies

Revision ID: c770958686f8
Revises: 3eef65ca8076
Create Date: 2026-07-10 11:17:35.608311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c770958686f8'
down_revision: Union[str, Sequence[str], None] = '3eef65ca8076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('likes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'likes')
    # ### end Alembic commands ###
